using './main.bicep'
param staticWebAppName = 'stapp-test'
param location = 'westeurope'
param skuStaticWebApp = 'Standard'
param skuCodeStaticWebApp = 'Standard'
param stagingEnvironmentPolicy = 'Disabled'
